---
# This role is used to deploy and config glance service

- name: Create glance DB
  mysql_db: name=glance state=present

- name: Create glance DB User
  mysql_user: host={{ item }} name=glance  password={{ glance_mysql_password }} priv=glance.*:ALL,GRANT state=present
  with_items:
    - "{{ mysql_vip }}"
    - "{{ inventory_hostname }}"
    - "{{ management_network }}"
    - localhost

- name: Install glance and glance client package
  yum: name={{ item }} state=present
  with_items:
   - openstack-glance
   - python-glanceclient

- name: Configure glance-api
  template: src=etc/glance/glance-api.conf.j2 dest=/etc/glance/glance-api.conf owner=glance group=glance mode=0640
  notify:
   - restart openstack-glance-api
   - restart openstack-glance-registry

- name: Configure glance-registry
  template: src=etc/glance/glance-registry.conf.j2 dest=/etc/glance/glance-registry.conf owner=glance group=glance mode=0640
  notify:
   - restart openstack-glance-api
   - restart openstack-glance-registry

- name: Glance DB sync
  command: /usr/bin/glance-manage db_sync

- name: Modify glance log file owner, because after db_sync it will be own by root
  file: path=/var/log/glance/api.log group=glance owner=glance

- name: Create glance user
  keystone_user:
    endpoint: "{{ keystone_admin_url_protocol }}://{{ keystone_admin_url_vip }}:{{ keystone_admin_url_port }}/v2.0"
    token: "{{ keystone_admin_token }}"
    user: glance
    password: "{{ glance_admin_password }}"
    email: "{{ glance_admin_email }}"
    tenant: services
    state: present

- name: Associate role admin with glance
  keystone_user:
    endpoint: "{{ keystone_admin_url_protocol }}://{{ keystone_admin_url_vip }}:{{ keystone_admin_url_port }}/v2.0"
    token: "{{ keystone_admin_token }}"
    user: glance
    tenant: services
    role: admin
    state: present

- name: Create Glance Endpoint
  keystone_service:
    endpoint: "{{ keystone_admin_url_protocol }}://{{ keystone_admin_url_vip }}:{{ keystone_admin_url_port }}/v2.0"
    token: "{{ keystone_admin_token }}"
    name: glance
    type: image
    region: regionOne
    description: "OpenStack Image Service"
    public_url: "{{ glance_service_url_protocol }}://{{ glance_service_url_vip }}:{{ glance_service_url_port }}"
    internal_url: "{{ glance_service_url_protocol }}://{{ glance_service_url_vip }}:{{ glance_service_url_port }}"
    admin_url: "{{ glance_service_url_protocol }}://{{ glance_service_url_vip }}:{{ glance_service_url_port }}"

- name: Start glance-api
  service: name=openstack-glance-api  state=started  enabled=yes

- name: Start glance-registry
  service: name=openstack-glance-registry  state=started  enabled=yes

- name: Mount /var/lib/glance/images
  mount: name=/var/lib/glance/images src={{ glance_image_nfs }} fstype=nfs opts="rw,bg,nointr,rsize=32768,wsize=32768,tcp,actimeo=0,vers=3,timeo=600,nolock" state=mounted

- name: Change dir owner
  file: name=/var/lib/glance/images state=directory owner=glance group=glance
