---
- name: restart neutron-openvswitch-agent
  service: name=neutron-openvswitch-agent state=restarted

- name: restart neutron-l3-agent
  service: name=neutron-l3-agent state=restarted

- name: restart neutron-lbaas-agent
  service: name=neutron-lbaas-agent state=restarted

- name: restart neutron-dhcp-agent
  command: killall dnsmasq
  ignore_errors: True
  notify: restart dhcp agent

- name: restart dhcp agent
  service: name=neutron-dhcp-agent  state=restarted

- name: restart neutron-metadata-agent
  command: killall neutron-ns-metadata-proxy
  ignore_errors: True
  notify: restart metadata agent

- name: restart metadata agent
  service: name=neutron-metadata-agent  state=restarted
  notify: restart neutron-l3-agent
