---
# directory and files

- name: ensure /etc/swift exists
  file: path=/etc/swift owner=swift group=swift mode=0750 state=directory

- name: Configure swift.conf file
  template: src=etc/swift/swift.conf.j2 dest=/etc/swift/swift.conf owner=swift group=swift mode=0600
  
- name: make sure /var/swift/recon exists
  file: path=/var/swift/recon state=directory owner=swift group=swift mode=0750

- name: ensure /etc/swift/*-server directories exist
  file: path=/etc/swift/{{ item }}-server state=directory owner=swift group=swift mode=0755
  with_items:
    - account
    - container
    - object
  
- name: Configure rsync config
  template: src=etc/rsyncd.conf.j2 dest=/etc/rsyncd.conf mode=0644
  notify:
   - restart rsyncd
   
- name: Configure swift 
  template: src=etc/swift/{{ item }}-server.conf.j2 dest=/etc/swift/{{ item }}-server.conf owner=swift group=swift mode=0640
  with_items:
   - account
   - container
   - object
  notify:
   - restart openstack-swift-account
   - restart openstack-swift-account-auditor
   - restart openstack-swift-account-reaper
   - restart openstack-swift-account-replicator
   - restart openstack-swift-container
   - restart openstack-swift-container-auditor
   - restart openstack-swift-container-replicator
   - restart openstack-swift-container-updater
   - restart openstack-swift-object
   - restart openstack-swift-object-auditor
   - restart openstack-swift-object-replicator
   - restart openstack-swift-object-updater
