---
- name: restart openstack-nova-api
  service: name=openstack-nova-api  state=restarted

- name: restart openstack-nova-cert
  service: name=openstack-nova-cert  state=restarted

- name: restart openstack-nova-consoleauth
  service: name=openstack-nova-consoleauth  state=restarted

- name: restart openstack-nova-scheduler
  service: name=openstack-nova-scheduler  state=restarted

- name: restart openstack-nova-conductor
  service: name=openstack-nova-conductor  state=restarted

- name: restart openstack-nova-novncproxy
  service: name=openstack-nova-novncproxy  state=restarted
