---
# Package

- name: Install swift package
  yum: name={{ item }} state=present
  with_items:
   - openstack-swift-proxy
   - python-swiftclient
   - python-keystonemiddleware
   - memcached
